export const English = {
  selectlocation: "Select Location",
  BuildgingName: "  Buildging Name",
  BuildgingId: "Buildging Id",
  AddBuilding: "Add Building",
  Cancel: "Cancel",
  Selectbuilding: "Select building",
  RoomName: "Room Name",
  RoomId: "Room Id",
  AddRoom: "Add Room",
  Selectroom: "Select room",
  ShelfName: "Shelf Name",
  ShelfId: "Shelf Id",
  Addshelf: " Add shelf",
  Selectshelf: "Select shelf",
  BoxFileName: "BoxFile Name",
  BoxFileId: "BoxFile Id",
  AddBoxFile: "Add BoxFile",
  SelectBoxfile: "Select Boxfile",
  FileName: "File Name",
  FileId: "File Id",
  AddFile: "AddFile",
  BuldingId: "Bulding Id",
  BuildingName: "Building Name",
  cancel: "Cancel",
  submit: "Submit",
  EditBuilding: "Edit Building",

  AddLocation: "Add Location",
  ViewLocation: "View Location",
  Buildings: "Buildings",
  Rooms: "Rooms",
  Shelfs: "Shelfs",
  BoxFiles: "Box Files",
  Files: "Files",
};
export const AMHARIC = {
  selectlocation: "ቦታ ምረጥ",
  BuildgingName: " ህንጻ ስም",
  BuildgingId: "ህንጻ ቁጥር",
  AddBuilding: "ህንጻ ጨምር",
  Cancel: "ሰርዝ",
  Selectbuilding: "ህንጻ ምረጥ",
  RoomName: "ክፍል ስም",
  RoomId: "ክፍል ቁጥር",
  AddRoom: "ክፍል ጨምር",
  Selectroom: "ክፍል ምረጥ",
  ShelfName: "መደርደሪያ ስም",
  ShelfId: "መደርደሪያ ቁጥር",
  Addshelf: "መደርደሪያ ጨምር",
  Selectshelf: "መደርደሪያ ምረጥ",
  BoxFileName: "የፋይልሳጥን ስም",
  BoxFileId: "የፋይልሳጥን ቁጥር",
  AddBoxFile: "የፋይልሳጥን ጨምር",
  SelectBoxfile: "የፋይልሳጥን ምረጥ",
  FileName: "የፋይል ስም",
  FileId: "የፋይል ቁጥር",
  AddFile: "ፋይል ጨምር",
  BuldingId: "ህንጻ ቁጥር",
  BuildingName: " ህንጻ ስም",
  cancel: "ሰርዝ",
  submit: "አስገባ",
  EditBuilding: "ህንጻ አሥተካክል",
  AddLocation: "አካባቢ ጨምር",
  ViewLocation: "አካባቢ ተመልከት",
  Buildings: "ሕንፃዎች",
  Rooms: "ክፍሎች",
  Shelfs: "መደርደሪያዎች",
  BoxFiles: "ሳጥን ፋይሎች",
  Files: "ፋይሎች",
};
