export const English = {
  selectlocation: "Select Location",
  BuildgingName: "  Buildging Name",
  BuildgingId: "Buildging Id",
  AddBuilding: "Add Building",
  Cancel: "Cancel",
  Selectbuilding: "Select building",
  RoomName: "Room Name",
  RoomId: "Room Id",
  AddRoom: "Add Room",
  Selectroom: "Select room",
  ShelfName: "Shelf Name",
  ShelfId: "Shelf Id",
  Addshelf: " Add shelf",
  Selectshelf: "Select shelf",
  BoxFileName: "BoxFile Name",
  BoxFileId: "BoxFile Id",
  AddBoxFile: "Add BoxFile",
  SelectBoxfile: "Select Boxfile",
  FileName: "File Name",
  FileId: "File Id",
  AddFile: "AddFile",
  BuldingId: "BuldingId",
  BuildingName: "BuildingName",
  incomming: "Incoming",
  outgoing: "Outgoing",
  addRecord: "Add Record",
  id: "Id",
  recordName: "Record Name",
  recipientOrg: "Recipient Organization",
  referenceNumber: "Reference Number",
  dateOfDispatch: "Date Of Dispatch",
  deliveryPersonnel: "Delivery Personnel",
  subject: "Subject",
  actions: "Actions",
  uploadRecord: "Upload Record",
  cancel: "Cancel",
  submit: "Submit",
  editRecord: "Edit Record",
  viewRecord: "View Record",
  fileName: "File Name",
  remark: "Remarks",
  detail: "Detail",
  addRemark: "Add Remark",
  title: "Title",
  listRemarks: "Remarks List",
  page: "Page",
  prev: "Prev",
  next: "Next",
  search: "Search",
  IncomingRecordDate: "Incoming Record Date",
  senderOrg: "Sender Organization",
  location: "Location",
  fillRecordInfo: "Fill Record Information",
  selectLocation: "select location",
  file: "File",
};
export const AMHARIC = {
  selectlocation: "ቦታ ምረጥ",
  BuildgingName: " ህንጻ ስም",
  BuildgingId: "ህንጻ ቁጥር",
  AddBuilding: "ህንጻ ጨምር",
  Cancel: "ሰርዝ",
  Selectbuilding: "ህንጻ ምረጥ",
  RoomName: "ክፍል ስም",
  RoomId: "ክፍል ቁጥር",
  AddRoom: "ክፍል ጨምር",
  Selectroom: "ክፍል ምረጥ",
  ShelfName: "መደርደሪያ ስም",
  ShelfId: "መደርደሪያ ቁጥር",
  Addshelf: "መደርደሪያ ጨምር",
  Selectshelf: "መደርደሪያ ምረጥ",
  BoxFileName: "የፋይልሳጥን ስም",
  BoxFileId: "የፋይልሳጥን ቁጥር",
  AddBoxFile: "የፋይልሳጥን ጨምር",
  SelectBoxfile: "የፋይልሳጥን ምረጥ",
  FileName: "የፋይል ስም",
  FileId: "የፋይል ቁጥር",
  AddFile: "ፋይል ጨምር",
  BuldingId: "ህንጻ ቁጥር",
  BuildingName: " ህንጻ ስም",
  incomming: "ገቢ",
  outgoing: "ወጪ",
  addRecord: "አዲስ መዝግብ",
  id: "መለያ",
  recordName: "የመዝገብ ስም",
  recipientOrg: "ተቀባይ ተቋም",
  referenceNumber: "የማጣቀሻ ቁጥር",
  dateOfDispatch: "የተላከበት ቀን",
  deliveryPersonnel: "ያደረሰው ስራተኛ",
  subject: "ርዕሰ ጉዳይ",
  actions: "ድርጊቶች",
  uploadRecord: "መዝገብ አስገባ",
  cancel: "አቋርጥ",
  submit: "አስገባ",
  editRecord: "አስተካክል",
  viewRecord: "መዝገብ ተመልከት",
  fileName: "የመዝገብ ስም",
  remark: "ይዘት",
  detail: "AM_Detail",
  title: "ርእስ",
  addRemark: "ይዘት ጨምር",
  listRemarks: "የይዘት ዝርዝር",
  page: "ገጽ",
  prev: "በፊት",
  next: "ቀጣይ",
  search: "ፈልግ",
  IncomingRecordDate: "የገቢ መዝገብ ቀን",
  senderOrg: "የላኪ ድርጅት ስም",
  location: "ቦታ",
  fillRecordInfo: "የመዝገብ መረጃን ሙላ",
  selectLocation: "ቦታ ይምረጡ",
  file: "ፋይል",
};
